version: "3.5"

services:
  cnab:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456

  app:
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3001:3000"
    depends_on:
      - cnab
    links:
      - cnab
